[package]
name = "bryanmaina-portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
console_error_panic_hook = "0.1.7"
console_log = "1"
log = "0.4"
leptos = { version = "0.8.2", features = ["nightly", "csr"] }
leptos_meta = "0.8.2"
leptos_router = { version = "0.8.2", features = ["nightly"] }
# gloo-net = "0.6.0"
leptos-use = { version = "0.16.0-beta", features = [
  "on_click_outside",
  "use_document",
  "use_media_query",
  "use_resize_observer",
  "use_toggle",
  "storage",
] }
reactive_stores = { version = "0.2.2" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
pulldown-cmark = "0.13.0"
gray_matter = "0.2.8"
reactive_stores_macro = "0.2.2"
# reactive_graph = { version = "0.2.2", features = ["effects"] }

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3", features = ["Document", "Window"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
