[toolchain]
# channel = "nightly-2025-04-14"
# current is "nightly-2025-05-12"
channel = "nightly"
components = ["cargo", "llvm-tools", "rust-src", "rust-std", "rustc", "rustc-dev", "rustfmt", "clippy"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
